<?php
session_start(); // Start session if needed
include('header.php');
?>

<!-- Link to the external CSS -->
<link rel="stylesheet" href="pe_pb_ratios_dropdown.css">

<!-- Page content -->
<section class="content">
    <br>
    <br>
    <h2 style="text-align: center;">P/E & P/B Ratio    </h2>
    
    <!-- Container for the iframe -->
    <div class="iframe-container">
        <iframe src="pe_pb_ratios_dropdown.html" class="embedded-frame" title="Price Movement Analysis"></iframe>
    </div>

    <br>
    <br>
    <!-- Extended Description Section -->
    <div class="description">
        <div class="card">
        <h3>P/E & P/B Ratio</h3>
<p>The Price-to-Earnings (P/E) Ratio and the Price-to-Book (P/B) Ratio are two essential metrics that investors use to evaluate the valuation and financial health of a company in the stock market. These ratios are crucial in determining whether a stock is overvalued, undervalued, or fairly priced, helping investors make informed decisions about buying or selling stocks.</p>

<p>P/E Ratio (Price-to-Earnings Ratio): The P/E ratio is calculated by dividing the stock's current price by its earnings per share (EPS). It helps investors understand how much they are paying for each dollar of earnings generated by the company. A higher P/E ratio suggests high growth expectations, whereas a lower P/E ratio may indicate a more stable or undervalued stock. However, comparing the P/E ratio of a company with its peers in the same industry is essential to understand its true valuation.</p>

<p>P/B Ratio (Price-to-Book Ratio): The P/B ratio compares the market value of a company's stock to its book value (the difference between the company's assets and liabilities). This ratio helps assess whether a stock is trading at a price higher or lower than the company's actual net assets. A P/B ratio of 1 indicates the stock price is equal to the book value, while a ratio higher than 1 suggests that investors expect the company to generate more value than its tangible assets. A ratio below 1 could mean that the stock is undervalued.</p>


        </div>
    </div>
</section>
<br>
<br>

<?php include('footer.php'); ?>
